### ISSUE TITLE
Fix BioPortal endpoint to get all provisional classes for a specific ontology

### ISSUE THREAD

**Issue by marcosmro** [metadatacenter/cedar-terminology-server#22]
The endpoint http://data.bioontology.org/ontologies/CEDARPC/provisional_classes returns all provisional classes for the CEDARPC ontology but includes some wrong results (wrong ontology). Example: the provisional class http://data.bioontology.org/provisional_classes/0dffc1c0-c2c8-0133-b244-005056010074 should not be returned.

**Comment by marcosmro** [comment]
Another example of the same issue: http://data.bioontology.org/ontologies/CEDARVS/provisional_classes

**Comment by martinjoconnor** [comment]
Will likely not be completed by BioPortal team in time for 0.8.
