### ISSUE TITLE
Index ontology branches in BioPortal

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-terminology-server#32]
BioPortal does not index ontology branches. As a result some branch searches quite a long time (several seconds) and searches in large branches can time out.

Latency can be particularly evident with pasting into spreadsheets with controlled terms (metadatacenter/cedar-project#787).

**Comment by marcosmro** [comment]
Here is an example of branch search call that takes a long time and ends up returning a 504 Gateway Time-out: http://data.bioontology.org/search?q=bacteria&ontology=NCBITAXON&subtree_root_id=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FNCBITAXON%2F131567

**Comment by graybeal** [comment]
idea: maybe we could index a few of the worst branches individually, and add a bit of code that checks to see if the ontology+subtree_root_id is indexed. If it is, make the query to the custom index for that call.

**Comment by martinjoconnor** [comment]
You mean at the BioPortal side?

**Comment by marcosmro** [comment]
We have discussed this issue with the BioPortal team. @mdorf and I will get together for a more technical analysis on how to enhance BioPortal's indexes to support faster subtree search, and to estimate the time needed to complete this task.

**Comment by marcosmro** [comment]
When CEDAR users enter values for a field that has been constrained to an ontology branch, CEDAR makes two different calls to BioPortal:

1) The first time that the user clicks on the field, CEDAR makes a call to BioPortal's "descendants" endpoint to retrieve all the classes in the branch.
2) When the user starts typing, CEDAR calls the "search" endpoint for the particular ontology branch that constrains the values of the field.

I've been testing the branch search calls and they work nicely. The example call shown above (http://data.bioontology.org/search?q=bacteria&ontology=NCBITAXON&subtree_root_id=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FNCBITAXON%2F131567), which was returning a time-out with the old index, is now returning results in 350ms approx. This is amazing, thanks @mdorf!

However, is seems that the "descendants" endpoint is still not taking advantage of the new index. For example, the following call should return all the descendants of the class "cellular organism" in NCBITAXON, however, it returns a timeout: http://data.bioontology.org/ontologies/NCBITAXON/classes/http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FNCBITAXON%2F131567/descendants?&page=1&pagesize=50&include=prefLabel,hasChildren,created,synonym,definition

Given that the new index contains all the information needed to support this query. It would be great if the BioPortal team could optimize BioPortal's descendants call to use the new index too.

Click on the following link if you want to check how the descendants/search calls work with a real CEDAR field, which as been constrained to the branch "cellular organism" from NCBITAXON: https://cedar.metadatacenter.org/instances/create/https://repo.metadatacenter.org/templates/1c76195e-81a7-40d0-852f-3f57bbcfc016?folderId=https:%2F%2Frepo.metadatacenter.org%2Ffolders%2F4095b42f-782c-482a-af94-ee01b6b2ce44

**Comment by mdorf** [comment]
A few observations:

a) The descendants call is entirely separate from the search in branches feature and should not be lumped in with this ticket. We should create a separate issue that tracks the descendants call.
b) The original /descendants endpoint should not be modified, as it acts consistently with the rest of the hierarchical endpoints (/ascendants, /parents, /children). The latter three cannot take advantage of the search index.
c) I can simulate the functionality you're seeking by enabling a queryless search in a branch. The signature will look like:

/search?ontology=SNOMEDCT&subtree_root_id=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FSNOMEDCT%2F64572001

This will return ALL descendants of the given class.

**Comment by marcosmro** [comment]
Sounds good. I will close this issue and create a new ticket.
