### ISSUE TITLE
Subsetting value sets at template design time

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-terminology-server#34]
Common use case for CDEs is to subset value sets at template design time.

Would be nice to allow user to subset.

Typically, the user will pick only a small set of exclusions (they will not, for example, do this for huge value sets) so we could store the exclusions in the field _valueConstraint specification).

**Comment by martinjoconnor** [comment]
Yup. It's also not too complex in terms of model representation to do it this way (though there are some details to handle on the front end).

**Comment by willrett** [comment]
Added
