### ISSUE TITLE
CORS requests not allowed b/c of Authorization header

### ISSUE THREAD

**Issue by dylanvaughn** [metadatacenter/cedar-terminology-server#6]
Hi @marcosmartinezromero - we are integrating this into the UI updates that we are working on for the create provisional classes feature.  However we are having an issue where a javascript error is returned when trying to create classes:

```XMLHttpRequest cannot load https://terminology.metadatacenter.net/bioportal/ontologies/CEDARPC/classes. Request header field  Authorization is not allowed by Access-Control-Allow-Headers in preflight response.```

We could resolve this by adding ```Authorization``` to this list:

https://github.com/metadatacenter/cedar-terminology-server/blob/develop/cedar-terminology-server-play/app/controllers/Application.java#L32

which is what we have done locally to get around this.

Also, in general should we be using your endpoint when working on this or our local endpoint?  We are still getting errors creating provisional classes after this fix with our local servers but haven't been able to track down the reason yet.

**Comment by marcosmartinezromero** [comment]
Hi @dylanvaughn - I have added 'Authorization' to the list. You may use our endpoint or your local one, we don't have any strong preference about that. Use the one that makes development easier for you. Let me know if you are still having problems when creating provisional classes. Thanks!

**Comment by dylanvaughn** [comment]
@marcosmartinezromero ok great thanks - did you deploy that change to terminology.metadatacenter.net?

**Comment by marcosmartinezromero** [comment]
Hi @dylanvaughn - I have just deployed it, but I see that the calls to the service are not working. The cause is probably some BioPortal issue. BioPortal main page is down right now. This problem should be solved during the day.
